"""add event_type enum

Revision ID: a4595573fac6
Revises: ddbd675eee0d
Create Date: 2026-04-13 15:34:32.341475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4595573fac6'
down_revision: Union[str, Sequence[str], None] = 'ddbd675eee0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('zajecia', 'wyklad', 'cwiczenia', 'projekt', 'laboratorium', 'egzamin', 'online', 'inne', name='eventtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'type',
               existing_type=sa.Enum('zajecia', 'wyklad', 'cwiczenia', 'projekt', 'laboratorium', 'egzamin', 'online', 'inne', name='eventtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
