"""add lecturers table

Revision ID: ddbd675eee0d
Revises: a2d5f33f3ef3
Create Date: 2026-04-04 14:20:01.060025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbd675eee0d'
down_revision: Union[str, Sequence[str], None] = 'a2d5f33f3ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('office_hours', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_index(op.f('ix_lecturers_id'), 'lecturers', ['id'], unique=False)
    op.add_column('events', sa.Column('lecturer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'lecturers', ['lecturer_id'], ['id'])
    op.create_foreign_key(None, 'events', 'schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'lecturer_id')
    op.drop_index(op.f('ix_lecturers_id'), table_name='lecturers')
    op.drop_table('lecturers')
    # ### end Alembic commands ###
